version: "3"

services:
  db_postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123

  rabbitmq:
    image: bitnami/rabbitmq:3.8.27
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_pass
      - RABBITMQ_DEFAULT_VHOST=/

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  worker:
    build: .
    command: celery -A TareasRedis worker --loglevel=INFO -Q celery --concurrency=1 -n worker@task01 --uid=nobody --gid=nogroup
    depends_on:
      - rabbitmq
      - cache

  django_app:
    build: .
    command: 'sh script.sh'
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
      - worker

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static: