# Generated by Django 3.2.5 on 2022-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.CharField(max_length=100)),
                ('numero2', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('operador', models.CharField(max_length=1)),
            ],
        ),
    ]
