# Generated by Django 3.2.5 on 2022-06-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='numero1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='numero2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='resultado',
            field=models.IntegerField(blank=True),
        ),
    ]
