# Generated by Django 3.2.5 on 2022-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_auto_20220609_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='resultado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
