# Generated by Django 3.2.5 on 2022-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_alter_operacion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='operador',
            field=models.CharField(max_length=3),
        ),
    ]
