# Generated by Django 3.2.5 on 2022-06-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_alter_operacion_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='operador',
            field=models.CharField(max_length=1),
        ),
    ]
